package com.nonoka.nhentai.domain.entity

const val NHENTAI_HOME = "https://nhentai.net"
const val NHENTAI_I = "https://i1.nhentai.net"
const val NHENTAI_T = "https://t1.nhentai.net"

const val CHINESE_LANG = "cn"
const val JAPANESE_LANG = "jp"
const val ENGLISH_LANG = "eng"

const val JPG = "jpg"
const val PNG = "png"
const val WEBP = "webp"
const val JPG_TYPE = "j"
const val PNG_TYPE = "p"
const val WEBP_TYPE = "w"

// Api constants
const val ID = "id"
const val MEDIA_ID = "media_id"
const val TITLE = "title"
const val IMAGES = "images"
const val PAGES = "pages"
const val IMAGE_TYPE = "t"
const val IMAGE_WIDTH = "w"
const val IMAGE_HEIGHT = "h"
const val SCANLATOR = "scanlator"
const val UPLOAD_DATE = "upload_date"
const val TAGS_LIST = "tags"
const val TYPE = "type"
const val NAME = "name"
const val URL = "url"
const val COUNT = "count"
const val NUM_PAGES = "num_pages"
const val NUM_FAVORITES = "num_favorites"
const val PER_PAGE = "per_page"
const val RESULT = "result"
const val COVER = "cover"
const val THUMBNAIL = "thumbnail"
const val TITLE_ENG = "english"
const val TITLE_JAPANESE = "japanese"
const val TITLE_PRETTY = "pretty"
const val ARTIST = "artist"
const val CHARACTER = "character"
const val CATEGORY = "category"
const val LANGUAGE = "language"
const val PARODY = "parody"
const val GROUP = "group"
const val TAG = "tag"

const val GALLERY_ID = "gallery_id"
const val POSTER = "poster"
const val USER_NAME = "username"
const val SLUG = "slug"
const val AVATAR_URL = "avatar_url"
const val IS_SUPER_USER = "is_superuser"
const val IS_STAFF = "is_staff"
const val POST_DATE = "post_date"
const val BODY = "body"

const val PAGE_INDEX = "page_index"